// Package anchordoc generates the canonical signing-anchor documentation — a
// managed, idempotent section embedded in an operator-owned file (conventionally
// SECURITY.md). It is the stable, committed, raw-URL-discoverable trust anchor that
// per-release Verification sections reference.
//
// Two boundaries are load-bearing:
//   - It owns ONLY the marked section; all surrounding prose (disclosure policy,
//     contact, incident process) stays the operator's. Whole-file ownership would
//     collapse the wrong things.
//   - It is generated by an EXPLICIT command, never silently during publish —
//     "publish distributes trust material; docs generation publishes trust
//     documentation" are different lifecycle events. No surprising repo mutation.
//
// Content is deterministic + idempotent: re-running with the same identity produces
// byte-identical output (no spurious diff). Room is left for historical fingerprints
// (rotation) without building it now.
package anchordoc

import (
	"errors"
	"fmt"
	"io/fs"
	"os"
	"strings"

	"github.com/PrPlanIT/StageFreight/src/sign/provision"
)

const (
	StartMarker = "<!-- sf:signing-anchor:start -->"
	EndMarker   = "<!-- sf:signing-anchor:end -->"
)

// tierFacts are the intrinsic assurance properties of an identity's tier — fixed
// and deterministic, so the disclosure never overstates trust.
type tierFacts struct {
	label            string
	transparency     bool
	humanAuth        bool
	nonExportableKey bool
}

func factsFor(tier string) tierFacts {
	switch tier {
	case provision.TierSoftware:
		return tierFacts{label: "Tier-0 (persistent software key)"}
	default:
		return tierFacts{label: tier}
	}
}

// Render produces the managed section's inner content (between the markers) for an
// identity and its public-key bytes. Deterministic.
func Render(id *provision.Identity, pubContents string) string {
	f := factsFor(id.Tier)
	yn := func(b bool) string {
		if b {
			return "yes"
		}
		return "no"
	}
	var b strings.Builder
	b.WriteString("## Signing Trust Anchor\n\n")
	b.WriteString("StageFreight release artifacts are signed using Sigstore Cosign.\n\n")
	b.WriteString("### Current Signing Identity\n\n")
	b.WriteString(fmt.Sprintf("- Tier: %s\n", f.label))
	b.WriteString(fmt.Sprintf("- Fingerprint: `%s`\n", id.Fingerprint))
	b.WriteString(fmt.Sprintf("- Transparency log: %s\n", yn(f.transparency)))
	b.WriteString(fmt.Sprintf("- Human authorization required: %s\n", yn(f.humanAuth)))
	b.WriteString(fmt.Sprintf("- Non-exportable key: %s\n\n", yn(f.nonExportableKey)))
	b.WriteString("### Public Key\n\n")
	b.WriteString("```text\n")
	b.WriteString(strings.TrimRight(pubContents, "\n"))
	b.WriteString("\n```\n\n")
	b.WriteString("### Verification\n\n")
	b.WriteString("See the per-release notes for the exact verification command and the trust evidence for that release.\n")
	return b.String()
}

// Update writes the managed signing-anchor section into file, replacing only the
// marked block and preserving all surrounding operator prose. Idempotent: the same
// identity yields a byte-identical file. Creates the file (with a minimal header) or
// appends the block when the markers are absent.
func Update(file, section string) error {
	block := StartMarker + "\n" + section + EndMarker

	existing, err := os.ReadFile(file)
	if errors.Is(err, fs.ErrNotExist) {
		return os.WriteFile(file, []byte("# Security\n\n"+block+"\n"), 0o644)
	}
	if err != nil {
		return err
	}
	text := string(existing)

	si := strings.Index(text, StartMarker)
	ei := strings.Index(text, EndMarker)
	if si >= 0 && ei > si {
		// Replace exactly start..end (inclusive); everything else stays verbatim.
		newText := text[:si] + block + text[ei+len(EndMarker):]
		if newText == text {
			return nil // idempotent no-op
		}
		return os.WriteFile(file, []byte(newText), 0o644)
	}

	// Markers absent → append a fresh block, preserving the existing content.
	newText := strings.TrimRight(text, "\n") + "\n\n" + block + "\n"
	return os.WriteFile(file, []byte(newText), 0o644)
}
