package lint

import (
	"testing"

	"github.com/PrPlanIT/StageFreight/src/config"
)

func TestClassifyProvenance(t *testing.T) {
	// rqlite-rs has a vendor marker; dragonfly-server (sibling under crates/) does not.
	roots := deriveVendoredRoots([]string{
		"crates/rqlite-rs/.cargo_vcs_info.json",
		"crates/rqlite-rs/src/client.rs",
		"crates/dragonfly-server/src/main.rs",
	})
	decl := config.ProvenanceConfig{
		Generated: []string{"static/tailwind.css"},
		Vendored:  []string{"patches/**"},
	}
	cases := []struct {
		name, path, head string
		want             ProvenanceKind
	}{
		{"authored-default", "src/main.rs", "fn main() {}", ProvenanceAuthored},
		{"lockfile-cargo-despite-@generated", "Cargo.lock", "# automatically @generated by Cargo.", ProvenanceLockfile},
		{"lockfile-npm", "package-lock.json", "{}", ProvenanceLockfile},
		{"lockfile-gosum", "go.sum", "", ProvenanceLockfile},
		{"generated-go-marker", "api.gen.go", "// Code generated by protoc. DO NOT EDIT.", ProvenanceGenerated},
		{"generated-at-marker", "schema.rs", "// @generated by thrift", ProvenanceGenerated},
		// A file that merely MENTIONS the marker deep down (this classifier, a fixture) is
		// NOT generated — the banner must be at the top.
		{"marker-deep-is-authored", "classifier.go", "package x\nimport \"y\"\nfunc a(){}\nfunc b(){}\nfunc c(){}\n// mentions @generated on line six", ProvenanceAuthored},
		{"config-generated", "static/tailwind.css", "body{}", ProvenanceGenerated},
		{"config-vendored", "patches/proxmox/Cargo.toml", "[package]", ProvenanceVendored},
		{"vendored-by-marker-root", "crates/rqlite-rs/src/client.rs", "use std;", ProvenanceVendored},
		{"vendored-marker-self", "crates/rqlite-rs/.cargo_vcs_info.json", "{}", ProvenanceVendored},
		{"sibling-NOT-vendored", "crates/dragonfly-server/src/main.rs", "fn main(){}", ProvenanceAuthored},
		{"vendored-by-path", "vendor/github.com/x/y.go", "package y", ProvenanceVendored},
	}
	for _, c := range cases {
		got := classifyProvenance(c.path, []byte(c.head), decl, roots)
		if got.Kind != c.want {
			t.Errorf("%s: got %v (source %q), want %v", c.name, got.Kind, got.Source, c.want)
		}
	}
}

func TestProvenanceFailsClosed(t *testing.T) {
	if !(Provenance{}).IsAuthored() {
		t.Error("zero-value provenance must be authored (full scrutiny)")
	}
	if (Provenance{}).RelaxHygiene() {
		t.Error("authored must NOT relax hygiene")
	}
	for _, k := range []ProvenanceKind{ProvenanceGenerated, ProvenanceVendored, ProvenanceLockfile} {
		if !(Provenance{Kind: k}).RelaxHygiene() {
			t.Errorf("%v must relax hygiene", k)
		}
	}
}
