package docsgen

import (
	"fmt"
	"strings"
)

const generatedHeader = "<!-- generated by stagefreight docs generate; do not edit manually -->\n\n"

// anchor generates a stable HTML anchor ID from a command path or config key.
func anchor(prefix, name string) string {
	id := prefix + "-" + strings.ReplaceAll(name, " ", "-")
	id = strings.ReplaceAll(id, ".", "-")
	return strings.ToLower(id)
}

// anchorTag returns an HTML anchor element for deep linking.
func anchorTag(prefix, name string) string {
	return fmt.Sprintf(`<a id="%s"></a>`, anchor(prefix, name))
}

// flagTable renders a markdown table for command flags.
func flagTable(rows []flagRow) string {
	if len(rows) == 0 {
		return ""
	}
	var b strings.Builder
	b.WriteString("| Name | Type | Default | Description |\n")
	b.WriteString("|------|------|---------|-------------|\n")
	for _, r := range rows {
		def := r.Default
		if def == "" {
			def = "—"
		}
		b.WriteString(fmt.Sprintf("| `%s` | %s | %s | %s |\n", r.Name, r.Type, def, r.Description))
	}
	return b.String()
}

// fieldTable renders a markdown table for config fields.
func fieldTable(rows []fieldRow) string {
	if len(rows) == 0 {
		return ""
	}
	var b strings.Builder
	b.WriteString("| Name | YAML Key | Type | Required | Default | Description |\n")
	b.WriteString("|------|----------|------|----------|---------|-------------|\n")
	for _, r := range rows {
		req := "No"
		if r.Required {
			req = "Yes"
		}
		def := r.Default
		if def == "" {
			def = "—"
		}
		b.WriteString(fmt.Sprintf("| `%s` | `%s` | %s | %s | %s | %s |\n",
			r.Name, r.YAMLKey, r.Type, req, def, r.Description))
	}
	return b.String()
}

type flagRow struct {
	Name        string
	Type        string
	Default     string
	Description string
}

type fieldRow struct {
	Name        string
	YAMLKey     string
	Type        string
	Required    bool
	Default     string
	Description string
}
