// Package gitlab lowers a forge-neutral model.Pipeline to GitLab CI YAML.
//
// The emitted file is a complete .gitlab-ci.yml — not a patch, not a fragment.
// It is the authoritative CI document for the repo, committed as generated source.
//
// Forge-specific lowering:
//   - RoutingSpec.Labels → tags:
//   - CapabilitySpec.Docker → .transport variables (DOCKER_HOST, TLS, certs)
//   - CapabilitySpec.OIDC → id_tokens.STAGEFREIGHT_OIDC
//   - PipelineDefaults.CIContext → before_script exporting SF_CI_* from CI_*
//   - PipelineDefaults.CancelSuperseded → workflow.auto_cancel.on_new_commit
//   - SourceSpec.FullClone → variables.GIT_DEPTH: 0
//   - PolicySpec.WhenAlways → when: always
//   - PolicySpec.AllowFailure → allow_failure: true
package gitlab

import (
	"bytes"
	"fmt"

	"github.com/PrPlanIT/StageFreight/src/ci/render/model"
)

const header = `# stagefreight-skeleton: universal
# provider: gitlab
# supports: audition, perform, review, publish, narrate
#
# GENERATED BY STAGEFREIGHT — DO NOT EDIT
# Regenerate: stagefreight ci render gitlab --write
#
# Universal lifecycle transport. One skeleton for all repo modes.
# StageFreight resolves modality from lifecycle.mode in .stagefreight.yml.
`

// Emit renders a forge-neutral Pipeline to GitLab CI YAML bytes.
func Emit(p model.Pipeline) ([]byte, error) {
	var buf bytes.Buffer

	buf.WriteString(header)

	// ── stages ──────────────────────────────────────────────────────────────
	buf.WriteString("\nstages:\n")
	for _, j := range p.Jobs {
		fmt.Fprintf(&buf, "  - %s\n", j.Stage)
	}

	// ── workflow ────────────────────────────────────────────────────────────
	if p.Defaults.CancelSuperseded {
		buf.WriteString("\nworkflow:\n")
		buf.WriteString("  auto_cancel:\n")
		buf.WriteString("    on_new_commit: interruptible\n")
	}

	// ── shared context anchor ──────────────────────────────────────────────
	if p.Defaults.CIContext {
		buf.WriteString("\n.stagefreight-context: &sf-context\n")
		for _, line := range ciContextExports() {
			fmt.Fprintf(&buf, "  - %s\n", line)
		}
	}

	// ── transport anchor ───────────────────────────────────────────────────
	if needsTransport(p) {
		buf.WriteString("\n.transport: &transport\n")
		buf.WriteString("  DOCKER_HOST: \"tcp://dind:2376\"\n")
		buf.WriteString("  DOCKER_TLS_VERIFY: \"1\"\n")
		buf.WriteString("  DOCKER_CERT_PATH: \"/certs/client\"\n")
	}

	// ── default ────────────────────────────────────────────────────────────
	buf.WriteString("\ndefault:\n")
	fmt.Fprintf(&buf, "  image: %s\n", p.Defaults.Image)
	if p.Defaults.Interruptible {
		buf.WriteString("  interruptible: true\n")
	}

	// ── jobs ────────────────────────────────────────────────────────────────
	for _, j := range p.Jobs {
		buf.WriteString("\n")
		emitJob(&buf, j, p.Defaults)
	}

	return buf.Bytes(), nil
}

func emitJob(buf *bytes.Buffer, j model.Job, defaults model.PipelineDefaults) {
	fmt.Fprintf(buf, "%s:\n", j.Name)
	fmt.Fprintf(buf, "  stage: %s\n", j.Stage)

	// id_tokens (OIDC)
	if j.Capabilities.OIDC {
		buf.WriteString("  id_tokens:\n")
		buf.WriteString("    STAGEFREIGHT_OIDC:\n")
		buf.WriteString("      aud: stagefreight\n")
	}

	// tags (routing)
	if len(j.Routing.Labels) > 0 {
		buf.WriteString("  tags:\n")
		for _, label := range j.Routing.Labels {
			fmt.Fprintf(buf, "    - %s\n", label)
		}
	}

	// needs
	if len(j.Needs) > 0 {
		if len(j.Needs) == 1 {
			fmt.Fprintf(buf, "  needs: [%s]\n", j.Needs[0])
		} else {
			buf.WriteString("  needs:\n")
			for _, n := range j.Needs {
				fmt.Fprintf(buf, "    - %s\n", n)
			}
		}
	}

	// variables (git depth + transport)
	hasVars := j.Source.FullClone || j.Capabilities.Docker
	if hasVars {
		buf.WriteString("  variables:\n")
		if j.Source.FullClone {
			buf.WriteString("    GIT_DEPTH: 0\n")
		}
		if j.Capabilities.Docker {
			buf.WriteString("    <<: *transport\n")
		}
	}

	// narrate needs BUILD_DATE
	if j.Name == "narrate" {
		if !hasVars {
			buf.WriteString("  variables:\n")
		}
		buf.WriteString("    BUILD_DATE: \"$CI_COMMIT_TIMESTAMP\"\n")
	}

	// before_script (CI context)
	if defaults.CIContext {
		buf.WriteString("  before_script:\n")
		buf.WriteString("    - *sf-context\n")
	}

	// script
	buf.WriteString("  script:\n")
	for _, cmd := range j.Commands {
		fmt.Fprintf(buf, "    - %s\n", cmd)
	}

	// artifacts
	if len(j.Artifacts.Paths) > 0 {
		buf.WriteString("  artifacts:\n")
		if len(j.Artifacts.Paths) == 1 {
			fmt.Fprintf(buf, "    paths: [%s]\n", j.Artifacts.Paths[0])
		} else {
			buf.WriteString("    paths:\n")
			for _, p := range j.Artifacts.Paths {
				fmt.Fprintf(buf, "      - %s\n", p)
			}
		}
		if j.Artifacts.ExpireIn != "" {
			fmt.Fprintf(buf, "    expire_in: %s\n", j.Artifacts.ExpireIn)
		}
	}

	// when: always
	if j.Policy.WhenAlways {
		buf.WriteString("  when: always\n")
	}

	// allow_failure
	if j.Policy.AllowFailure {
		buf.WriteString("  allow_failure: true\n")
	}
}

// ciContextExports returns the SF_CI_* export lines for GitLab.
func ciContextExports() []string {
	return []string{
		`export SF_CI_PROVIDER=gitlab`,
		`export SF_CI_EVENT="${CI_PIPELINE_SOURCE}"`,
		`export SF_CI_BRANCH="${CI_COMMIT_BRANCH}"`,
		`export SF_CI_TAG="${CI_COMMIT_TAG}"`,
		`export SF_CI_SHA="${CI_COMMIT_SHA}"`,
		`export SF_CI_DEFAULT_BRANCH="${CI_DEFAULT_BRANCH}"`,
		`export SF_CI_REPO_URL="${CI_PROJECT_URL}"`,
		`export SF_CI_WORKSPACE="$PWD"`,
		`export SF_CI_PIPELINE_ID="${CI_PIPELINE_ID}"`,
	}
}

// needsTransport returns true if any job requires Docker capability.
func needsTransport(p model.Pipeline) bool {
	for _, j := range p.Jobs {
		if j.Capabilities.Docker {
			return true
		}
	}
	return false
}
