package cmd

import (
	"github.com/spf13/cobra"
)

var ciCmd = &cobra.Command{
	Use:   "ci",
	Short: "CI subsystem commands",
	Long: `Provider-neutral CI entry points.

Generated CI files translate forge-native context into SF_CI_* environment
variables, then call stagefreight ci run <phase>. Phase behavior is
configured in .stagefreight.yml. CI files are generated by ci render.`,
}

func init() {
	rootCmd.AddCommand(ciCmd)
}
